const DEFAULT_MARKETPLACE_ADDRESS = '0x7Ac337E8e335daB629F868f811AfA40986418616';
const DEFAULT_NFT_ADDRESS = '0xd3c19abB9af47b9E0c8dD4AE6471FaE52F674A4d';
const DEFAULT_ARC_RPC_URL = 'https://rpc.testnet.arc.network';
const DEFAULT_USDC_ADDRESS = '0x3600000000000000000000000000000000000000';

const {
  VITE_INVOICE_MARKETPLACE_ADDRESS,
  VITE_INVOICE_NFT_ADDRESS,
  VITE_ARC_RPC_URL,
  VITE_ARC_RPC_URLS,
  VITE_USDC_ADDRESS,
} = import.meta.env;

export const INVOICE_MARKETPLACE_ADDRESS =
  VITE_INVOICE_MARKETPLACE_ADDRESS || DEFAULT_MARKETPLACE_ADDRESS;

export const INVOICE_NFT_ADDRESS =
  VITE_INVOICE_NFT_ADDRESS || DEFAULT_NFT_ADDRESS;

export const ARC_RPC_URL = VITE_ARC_RPC_URL || DEFAULT_ARC_RPC_URL;

const additionalRpcUrls = (VITE_ARC_RPC_URLS || '')
  .split(',')
  .map(url => url.trim())
  .filter(Boolean);

export const ARC_RPC_URLS = [ARC_RPC_URL, ...additionalRpcUrls].filter(
  (value, index, self) => self.indexOf(value) === index,
);

export const CONTRACT_ADDRESSES = {
  marketplace: INVOICE_MARKETPLACE_ADDRESS,
  invoiceNft: INVOICE_NFT_ADDRESS,
  usdc: VITE_USDC_ADDRESS || DEFAULT_USDC_ADDRESS,
};

